# Generated by Django 4.0.5 on 2022-07-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='vote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
